# Generated by Django 2.0.4 on 2018-04-28 16:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SN', '0004_auto_20180428_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='profile_pic',
            field=models.FileField(default='settings.MEDIA_ROOT/anonymous.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='snuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
